# Generated by Django 3.1.3 on 2023-04-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0002_auto_20230425_0645'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='course_id',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
        migrations.AddField(
            model_name='question',
            name='lesson_id',
            field=models.ManyToManyField(to='onlinecourse.Lesson'),
        ),
    ]
