# Generated by Django 3.1.3 on 2023-04-25 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_auto_20230425_0848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_id',
            field=models.ManyToManyField(default=None, to='onlinecourse.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='grade',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson_id',
            field=models.ManyToManyField(default=None, to='onlinecourse.Lesson'),
        ),
    ]
