# Generated by Django 3.1.3 on 2023-04-25 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0004_auto_20230425_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='onlinecourse.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson_id',
            field=models.ManyToManyField(blank=True, default=None, null=True, to='onlinecourse.Lesson'),
        ),
    ]
