# Generated by Django 3.1.3 on 2023-04-25 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0005_auto_20230425_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='course_id',
            field=models.ManyToManyField(to='onlinecourse.Course'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lesson_id',
            field=models.ManyToManyField(to='onlinecourse.Lesson'),
        ),
    ]
