# Generated by Django 3.1.3 on 2023-04-25 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0006_auto_20230425_0921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='course_id',
        ),
        migrations.RemoveField(
            model_name='question',
            name='lesson_id',
        ),
    ]
